### ISSUE TITLE
Add in voting system

### ISSUE THREAD

**Issue by james-vaughn** [ViralKrieger/composr#1]
We need to allow attendees to only vote on songs instead of add them directly.

We need to add in upvote/downvote buttons and then have the playlist manager register the song votes.

**Comment by littlebigrob** [comment]
added the back end for each use to vote on each song but now need the buttons

**Comment by james-vaughn** [comment]
We need to figure out how we want to display the current vote and the number

**Comment by frankhucek** [comment]
will be added soon. just got add songs working for admins.

**Comment by littlebigrob** [comment]
added a bare bones version but now needs to effect the user vote list aswell
