### ISSUE TITLE
Party Page functionality should reflect User type

### ISSUE THREAD

**Issue by ViralKrieger** [ViralKrieger/composr#18]
- Display buttons according to if the User is an Attendee, Admin, or Party Host
   - This can be worked on before #16 is implemented, you can assume you know the User type when a user loads the web page
- Party Host
   - Play, pause buttons
   - All functionality that the Admin has
- Admin
   - Removing songs
   - Reorder songs (are we still doing this?)
   - Can manipulate Admin Playlist

**Comment by james-vaughn** [comment]
I added user classes and have the party page displaying different actions depending on user type.
