### ISSUE TITLE
Make the party codes affect what user class is applied

### ISSUE THREAD

**Issue by james-vaughn** [ViralKrieger/composr#2]
Right now both admin and attendee codes get you into the party, but they do not change what user class is set, so everyone is treated as an admin.

We need to set up new users upon joining a party and set their user class.

**Comment by littlebigrob** [comment]
need to add cookies to distingish which users are which

**Comment by frankhucek** [comment]
look into sessions in django. this should handle users very easily. i think the thing we need to do is store users with their associated party code. Doesn't a party store all its users anyway?

**Comment by ViralKrieger** [comment]
Moved to #16
