### ISSUE TITLE
increase code covered by tests

### ISSUE THREAD

**Issue by littlebigrob** [ViralKrieger/composr#9]

**Comment by littlebigrob** [comment]
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
music\__init__.py                               0      0   100%
music\party.py                                 63     10    84%
music\playlist_manager.py                      51     37    27%
music\song_info.py                             26      0   100%
music\spotify_relay.py                         91     38    58%
music\user.py                                  35      0   100%
run_all_tests.py                                7      0   100%
tests\unit-tests\test_party.py                 79      8    90%
tests\unit-tests\test_playlist_manager.py      64     49    23%
tests\unit-tests\test_song_info.py             38      1    97%
tests\unit-tests\test_spotify_relay.py         28     15    46%
tests\unit-tests\test_user.py                  48      1    98%
---------------------------------------------------------------
TOTAL                                         530    159    70%

**Comment by littlebigrob** [comment]
Name                                                    Stmts   Miss  Cover
---------------------------------------------------------------------------
composr\__init__.py                                         0      0   100%
composr\settings.py                                        20      0   100%
composr\urls.py                                             3      0   100%
manage.py                                                  13      6    54%
music\__init__.py                                           0      0   100%
music\admin.py                                              1      0   100%
music\apps.py                                               3      0   100%
music\migrations\__init__.py                                0      0   100%
music\models.py                                             1      0   100%
music\party.py                                             90     26    71%
music\playlist_manager.py                                  51      0   100%
music\song_info.py                                         26      0   100%
music\spotify_relay.py                                     88     40    55%
music\tests\__init__.py                                     0      0   100%
music\tests\acceptance-tests\TestSystemActions.py          14      4    71%
music\tests\acceptance-tests\__init__.py                    0      0   100%
music\tests\acceptance-tests\test_party_actions.py         14      4    71%
music\tests\acceptance-tests\test_playlist_actions.py      14      4    71%
music\tests\acceptance-tests\test_user_actions.py          14      4    71%
music\tests\unit-tests\__init__.py                          0      0   100%
music\tests\unit-tests\test_party.py                       77      0   100%
music\tests\unit-tests\test_playlist_manager.py            93      0   100%
music\tests\unit-tests\test_song_info.py                   36      0   100%
music\tests\unit-tests\test_spotify_relay.py               27     15    44%
music\tests\unit-tests\test_user.py                        46      0   100%
music\urls.py                                               4      0   100%
music\user.py                                              35      0   100%
music\views.py                                             47     31    34%
---------------------------------------------------------------------------
TOTAL                                                     717    134    81%

**Comment by james-vaughn** [comment]
Added the selenium tests which helped a bit.

**Comment by james-vaughn** [comment]
Looks like all the code is now covered that can be
